### ISSUE TITLE
Random auctions displayed

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1378]
https://sky.coflnet.com/item/MOLTEN_NECKLACE?mana_regeneration=4-6&veteran=4-6&range=active  

Website randomly loads items not matching filter and adds them like other search results. The `Lowestprice` api endpoint can not return other elements that are a lower price later
![Image](https://github.com/user-attachments/assets/4399e3b2-3a8d-4287-8f05-34e56ca484ff)

**Comment by Ekwav** [comment]
there is another request sent without any filters and the result is added

**Comment by matthias-luger** [comment]
fixed by 73a1a85bd50743db7121a2b374ae945ec7e1e553

**Comment by Ekwav** [comment]
still happens for example with https://sky.coflnet.com/item/SNIPER_BOW?Rarity=EPIC&range=active, the first element is already wrong

**Comment by matthias-luger** [comment]
now hopefully fixed by f91486ec3714ec69cbdd5a158e96f4a3233aa532
