### ISSUE TITLE
Sold is not parsed correctly

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#202]
The frontend rans into an exception when it receives a `sold` command.
```
Uncaught SyntaxError: Unexpected token f in JSON at position 3
    at JSON.parse (<anonymous>)
```

**Comment by matthias-luger** [comment]
should be fixed @Ekwav

**Comment by Ekwav** [comment]
Yep, you forgot to reference the issue in the pull-Request #195
